### ISSUE TITLE
decimal requirement specificity causes issues with other hex packages

### ISSUE THREAD

**Issue by sparta-developers** [Qqwy/elixir-number#1]
We are trying to add a package that depends upon numbers, and are running into an issue due to the specificity of the `decimal` version. Currently, numbers locks to `~> 1.3.0`. We are currently using `1.4.0`.

So long as decimal correctly follows semver and does not break backwards compatibility with minor releases, it seems like numbers could be slightly less specific... maybe `~> 1.3`? I'm not sure if there is a reason for being so specific.

Thanks!

**Comment by Qqwy** [comment]
:+1:  This should have been fixed a long time ago. Decimal follows Semver properly, so the version should indeed be less specific. I'll resolve it right away. 

My apologies for taking so long to get back to you; GitHub notifications are... odd.

**Comment by Qqwy** [comment]
Fixed in df3dfe0a87d3ed4758f9db0c6bee3ae8c0db700f :slightly_smiling_face: .
