### ISSUE TITLE
use decimal version 2.0

### ISSUE THREAD

**Issue by peaceful-james** [Qqwy/elixir-number#24]
Are there any plans to update decimal version to 2.0?

I cannot install https://github.com/akoutmos/doctor with https://hex.pm/packages/ex_cldr_units because ex_cldr_units uses ratio which uses numbers which is stuck on decimal 1.9 and doctor uses 2.0

**Comment by Qqwy** [comment]
Thank you for the heads-up!
I definitely want Numbers to be Decimal 2.0 compatible. 

Feel free to open a PR if you want. 
Otherwise I hope to find time for this myself this weekend.

**Comment by peaceful-james** [comment]
I made a PR for this 
https://github.com/Qqwy/elixir-number/pull/25

**Comment by peaceful-james** [comment]
This is fixed in v5.2.4
